<?php
	use Zend\Session\Container;
	$sessionUser = new Container ( 'user' );
?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php 
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/bootstrap/css/bootstrap.min.css' );
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/style.css' );
	?>
</head>
<body>
	<div style="height: 40px; text-align: center; font-size: 60px; color: #0000ff">3 D 打 印 模 型</div>
	<div class="container">
		<div>
			<ul class="nav navbar-nav navbar-right">
				<?php
				if ($sessionUser->name != NULL) {
					?>	
					<li>欢迎: <?php echo $sessionUser->name?></li>
					<li><a href="/sandi/upload-model">上传模型</a></li>
					<li><a href="/user/index/<?php echo $sessionUser->user_id ?>">我的信息</a></li>
					<li><a href="/user/logout">退出</a></li>
				<?php
				} else {
					?>
					<li><a href="/user/login">登录</a></li>
					<li><a href="/user/add">注册</a></li>
				<?php
				}
				?>
	        </ul>
		</div>
	</div>
	<div class="container">
		<nav class="navbar navbar-default">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<?php 
					foreach ( $category as $column => $categoryData):
						echo '<li><a href="/sandi/index/' . $categoryData->category_id . '">' . $categoryData->title . "</a></li>" ;
					endforeach;
					?>
				</ul>
				<form class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
			<!-- /.navbar-collapse -->
		</nav>
	</div>

	<div class="container">
		<h1>编辑模型</h1>

		<?php
		$form = $this->form;

		$form->setAttribute ( 'action', $this->url ( 'sandi', array (
				'action' => 'edit',
				'id' => $this->id 
		) ) );
		$form->prepare ();

	
		echo $this->form ()->openTag ( $form );
		echo $this->formHidden ( $form->get ( 'model_id' ) ) . "<br><br>";
		echo $this->formHidden ( $form->get ( 'user_id' ) ) . "<br><br>";
		echo $this->formRow ( $form->get ( 'profile' ) ) . "<br><br>";
		echo $this->formRow ( $form->get ( 'price' ) ) . "<br><br>";
		echo $this->formRow ( $form->get ( 'offer' ) ) . "<br><br>";
		echo $this->formRow ( $form->get ( 'category' ) ) . "<br><br>";
		//$fileElement = $form->get ( 'image-file' );
		// echo $this->formLabel ( $fileElement ) . "<br><br>";
		// echo $this->formFile ( $fileElement ) . "<br><br>";
		// echo $this->formElementErrors ( $fileElement ) . "<br><br>";
		echo $this->formSubmit ( $form->get ( 'submit' ) ) . "<br><br>";
		echo $this->form ()->closeTag ();
		?>
	</div>

	<div class="container">
	<a href="/sandi/upload-Model-Image-File/<?php echo $this->id; ?>" >更新模型图片</a>
	</div>
