<?php
ini_set('default_charset','gb2312');

$title = 'Edit model';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<?php
$form = $this->form;
$form->setAttribute('action', $this->url(
    'sandi',
    array(
        'action' => 'edit',
        'id'     => $this->id,
    )
));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('model_id')). "<br><br>";
echo $this->formHidden($form->get('user_id')). "<br><br>";
echo $this->formRow($form->get('profile')). "<br><br>";
echo $this->formRow($form->get('price')). "<br><br>";
echo $this->formRow($form->get('offer')). "<br><br>";			
echo $this->formRow($form->get('category')). "<br><br>";
$fileElement = $form->get('image-file');
echo $this->formLabel($fileElement). "<br><br>";
echo $this->formFile($fileElement). "<br><br>";
echo $this->formElementErrors($fileElement). "<br><br>";
echo $this->formSubmit($form->get('submit')). "<br><br>";
echo $this->form()->closeTag();
