<?php 
//$local = new Zend_Locale();
//ini_set('default_charset','gb2312');
use Zend\Session\Container;
$sessionUser = new Container('user');
//echo $sessionUser->user_id;

?>
<html>
<head>
    <title>3D模型</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
<?php
    echo $this->headLink()->prependStylesheet($this->basePath() . '/bootstrap/css/bootstrap.min.css');
    echo $this->headLink()->prependStylesheet($this->basePath() . '/css/style.css');	
?>	
</head>
<body>

<div style="height:120px;text-align:center;font-size: 20px;">
    3D  模型
</div>
<div class="container">
    <nav class="navbar navbar-default" role="navigation">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse navbar-ex1-collapse">
            <ul class="nav navbar-nav">
                <li class="active"><a href = "/sandi/index/1">Handicraft</a></li>
                <li><a href = "/sandi/index/2">Artist</a></li>
				<li><a href = "/sandi/index/3">ee</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="#">Something else here</a></li>
                        <li class="divider"></li>
                        <li><a href="#">Separated link</a></li>
                        <li class="divider"></li>
                        <li><a href="#">One more separated link</a></li>
                    </ul>
                </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="src/html/cart.html"><i class="glyphicon glyphicon-shopping-cart"></i></a></li>
				<?php
				if ($sessionUser->name != NULL)
				{
				?>	
					<li><b>welcome: <?php echo $sessionUser->name?></b></li>
					<li><a href = "/sandi/upload-model">upload model</a></li>
					<li><a href = "/user/index/<?php echo $sessionUser->user_id ?>">My Information</a></li>
					<li><a href = "/user/logout">Log out</a></li>
				<?php 
				}
				else
				{?>
					<li><a href = "/user/login">log in </a></li> 
					<li><a href = "/user/add">sign up</a> </li>
				<?php 
				}
				?>
            </ul>
        </div><!-- /.navbar-collapse -->
    </nav>
</div>


<div class="container">

<?php 
if ($informID== 1)
{?>	
<h>Upload Model successfully!</h>
<?php 
}
if ($informID== 2)
{?>
<h>Modify Model successfully!</h>
<?php 
}
?>
<h1><a href = "/sandi/index">home</a></h1>
</div>