<?php 
ini_set('default_charset','gb2312');
use Zend\Session\Container;
$sessionUser = new Container('user');

$purchaseFlag = ($grant[0]['grant_bitmap'] >> 1) & 1;
$printFlag = ($grant[0]['grant_bitmap'] >> 2) & 1;
$downloadFlag = ($grant[0]['grant_bitmap'] >> 3) & 1;
echo "purchaseFlag ". $purchaseFlag . "<br>";
echo "printFlag " .$printFlag . "<br>";
echo "downloadFlag " . $downloadFlag . "<br>";

if ($sessionUser->name != NULL)
{
?>	<h>欢迎您：<?php echo $sessionUser->name?> &nbsp;&nbsp;<a href = "/sandi/upload-model">上传模型</a>&nbsp;&nbsp;<a href = "/user/logout">退出</a></h>
<?php 
}
else
{?>
<h>您还没登录！ <br> <a href = "/user/login">登录</a> <a href = "/user/add">注册新用户</a> </h>
<?php 
}
?>
<h><br> <a href = "/sandi/index">主页</a> </h>


<table class="table">
<tr>
    <th>model id</th>
    <th>profile</th>
	<th>&nbsp;</th>
	<th>&nbsp;</th>
</tr>
<?php 
//define('S_ROOT', dirname(__FILE__).DIRECTORY_SEPARATOR);
define("SITE_PATH", $this->serverUrl());
//echo $this->url('home');
?>
<tr>
    <td><?php echo $this->escapeHtml($model[0]["model_id"]);?></td>
    <td><?php echo $this->escapeHtml($model[0]["profile"]);?></td>
	<!--<td>php echo $this->escapeHtml($model->contents);</td>-->
    <td><img src= '<?php echo SITE_PATH . '/3d-model-file/' . $model->model_id. '/11.png'?>' /></td>
	<td><?php 
		if ($purchaseFlag == 4) 
		{
			echo "已购买";
		}
		else
		{
					if ($printFlag == 1) 
					{
		?>
						<a href="<?php echo $this->url('sandi', array('action'=>'modelPrint', 'id' => $model->model_id));?>">Print model</a>
		<?php 
					}
					
					if ($downloadFlag == 1) 
					{
		?>
						<a href="<?php echo $this->url('sandi', array('action'=>'modelDownload', 'id' => $model->model_id));?>">Download model</a>
		<?php 
					}					
					
		}
		?>
	</td>
	<td>
		<?php if ($sessionUser->user_id == $model[0]["owner_id"]) {?>
		<a href="<?php echo $this->url('sandi', array('action'=>'edit', 'id' => $model[0]["model_id"]));?>">编辑模型</a>
		<?php 
		}
		else
		{?>
		<h>-- </h>
		<?php 
		}
		?>	  		
    </td>
</tr>
</table>
