<?php
use Zend\Session\Container;
$sessionUser = new Container ( 'user' );

$purchaseFlag = ($grant [0] ['grant_bitmap'] >> 1) & 1;
$printFlag = ($grant [0] ['grant_bitmap'] >> 2) & 1;
$downloadFlag = ($grant [0] ['grant_bitmap'] >> 3) & 1;
?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php
	echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/bootstrap/css/bootstrap.min.css' );
	echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/style.css' );
	?>	
</head>
<body>
	<div style="height: 40px; text-align: center; font-size: 60px; color: #0000ff">3 D 打 印 模 型</div>
	<div class="container">
		<div>
			<ul class="nav navbar-nav navbar-right">
				<?php
				if ($sessionUser->name != NULL) {
					?>	
					<li>欢迎: <?php echo $sessionUser->name?></li>
					<li><a href="/sandi/upload-model">上传模型</a></li>
					<li><a href="/user/index/<?php echo $sessionUser->user_id ?>">我的信息</a></li>
					<li><a href="/sandi/purchase-list">我的订单</a></li>
					<li><a href="/user/logout">退出</a></li>
				<?php
				} else {
					?>
					<li><a href="/user/login">登录</a></li>
					<li><a href="/user/add">注册</a></li>
				<?php
				}
				?>
	        </ul>
		</div>
	</div>
	<div class="container">
		<nav class="navbar navbar-default">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse"
					data-target=".navbar-ex1-collapse">
					<span class="sr-only">Toggle navigation</span> <span
						class="icon-bar"></span> <span class="icon-bar"></span> <span
						class="icon-bar"></span>
				</button>
			</div>
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<?php 
					foreach ( $category as $column => $categoryData):
						echo '<li><a href="/sandi/index/' . $categoryData->category_id . '">' . $categoryData->title . "</a></li>" ;
					endforeach;
					?>
				</ul>
				<form class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
			<!-- /.navbar-collapse -->
		</nav>
	</div>
	
	<div class="container">

		<div class="row row-offcanvas row-offcanvas-right">

			<div class="col-sm-6 col-md-3">
				<div  class=thumbnail>
					<img src="<?php echo $this->url('sandi', array('action'=>'showBiggerModelImage', 'id' =>$model[0]["model_id"]));?>" />
					<p><?php echo $this->escapeHtml($model[0]["profile"]);?></p>
					<p>价格: <?php echo $this->escapeHtml($offer[0]["contents"]);?> 元</p>
				</div>
			</div>
			<div class="col-xs-6 col-sm-4 sidebar-offcanvas cart-list"
				id="sidebar" role="navigation">
			<?php if ($sessionUser->user_id == $model[0]["owner_id"]) {?>
				<a href="<?php echo $this->url('sandi', array('action'=>'edit', 'id' => $model[0]["model_id"]));?>">编辑模型</a>
			<?php
			} else {
				?>
			<h>
				<?php
					if ($hasPurchased == true)
					{?>
						<a href="<?php echo $this->url('sandi', array('action'=>'downloadModel', 'id' => $offer[0]["offer_id"]));?>"> 下载模型</a>					
					<?php
					}
					else 
					{
						if ($printFlag == 1)
						{?>
							<a href="<?php echo $this->url('sandi', array('action'=>'purchaseModel', 'id' => $offer[0]["offer_id"], 'subaction' => 4));?>">购买打印权</a>
					<?php
						}
						
						if ($downloadFlag == 1)
						{?>
							<a href="<?php echo $this->url('sandi', array('action'=>'purchaseModel', 'id' => $offer[0]["offer_id"], 'subaction' => 8));?>">购买下载权</a>
					<?php
						}
					}
				?>
			</h>
			<?php
			}
			?>	
        </div>
		</div>
	</div>
</body>
</html>