<?php
	use Zend\Session\Container;
	$sessionUser = new Container ( 'user' );
?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php 
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/bootstrap/css/bootstrap.min.css' );
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/style.css' );
	?>
</head>
<body>
	<div style="height: 40px; text-align: center; font-size: 60px; color: #0000ff">3 D 打 印 模 型</div>
	<div class="container">
		<div>
			<ul class="nav navbar-nav navbar-right">
				<?php
				if ($sessionUser->name != NULL) {
				?>	
					<li>欢迎: <?php echo $sessionUser->name?></li>
					<li><a href="/sandi/upload-model">上传模型</a></li>
					<li><a href="/user/index/<?php echo $sessionUser->user_id ?>">我的信息</a></li>
					<li><a href="/sandi/purchase-list">我的订单</a></li>
					<li><a href="/user/logout">退出</a></li>
				<?php
				} 
				else 
				{
				?>
					<li><a href="/user/login">登录</a></li>
					<li><a href="/user/add">注册</a></li>
				<?php
				}
				?>
	        </ul>
		</div>
	</div>
	<div class="container">
		<nav class="navbar navbar-default">
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<?php 
					foreach ( $category as $column => $categoryData):
						echo '<li><a href="/sandi/index/' . $categoryData->category_id . '">' . $categoryData->title . "</a></li>" ;
					endforeach;
					?>
				</ul>
				<form class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
		</nav>
	</div>
	
	<table>
		<tr height = 50>
			<td span=3><b>上传模型分三步：</b> 1. 填写模型基本信息  &nbsp&nbsp&nbsp 2. 上传模型图片文件&nbsp&nbsp&nbsp 3. 上传模型工程文件</td>
		</tr>	
		<tr>
			<td height=300>
				<?php 	
					$form = $this->form;
					$form->setAttribute ( 'action', $this->url ( 'sandi', array (
							'action' => 'uploadModel'
					) ) );
					$form->prepare();
					echo $this->form()-> openTag( $form ); 
				?>
				    <div class="form-element">
						<?php echo $this->formHidden($form->get('model_id')); ?>
						<?php echo $this->formHidden($form->get('user_id')); ?>
						<?php echo $this->formRow($form->get('profile')); ?><br>
						<?php echo $this->formRow($form->get('price')); ?><br>
						<?php echo $this->formRow($form->get('tag')); ?><br>
						<?php echo $this->formRow($form->get('offer')); ?><br>
						<?php echo $this->formRow($form->get('category')); ?><br>
				        <?php //echo utf8_decode($this->formRow($form->get('profile'))); ?>
				        
				        <?php echo $this->formSubmit ( $form->get ( 'submit' ) );?>
					</div>
					
	
					<?php echo $this->form()->closeTag(); ?>
			</td>
			<td></td>
			<td></td>
		</tr>	
	</table>
</body>
</html>
