<?php
	use Zend\Session\Container;
	$sessionUser = new Container ( 'user' );
?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php 
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/bootstrap/css/bootstrap.min.css' );
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/style.css' );
	?>
</head>
<body>
	<div style="height: 40px; text-align: center; font-size: 60px; color: #0000ff">3 D 打 印 模 型</div>
	<div class="container">
		<div>
			<ul class="nav navbar-nav navbar-right">
				<?php
				if ($sessionUser->name != NULL) {
				?>	
					<li>欢迎: <?php echo $sessionUser->name?></li>
					<li><a href="/sandi/upload-model">上传模型</a></li>
					<li><a href="/user/index/<?php echo $sessionUser->user_id ?>">我的信息</a></li>
					<li><a href="/sandi/purchase-list">我的订单</a></li>
					<li><a href="/user/logout">退出</a></li>
				<?php
				} 
				else 
				{
				?>
					<li><a href="/user/login">登录</a></li>
					<li><a href="/user/add">注册</a></li>
				<?php
				}
				?>
	        </ul>
		</div>
	</div>
	<div class="container">
		<nav class="navbar navbar-default">
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<?php 
					foreach ( $category as $column => $categoryData):
						echo '<li><a href="/sandi/index/' . $categoryData->category_id . '">' . $categoryData->title . "</a></li>" ;
					endforeach;
					?>
				</ul>
				<form class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
		</nav>
	</div>

	<div class="container">
		<?php  $form = $this->form; $form->prepare(); ?>
		<?php echo $this->form()->openTag( $form ); ?>
	    <div class="form-element">
	        <?php $fileElement = $form->get('model-project-file'); ?>
	        <?php echo $this->formLabel($fileElement); ?>
	        <?php echo $this->formFile($fileElement); ?>
	        <?php echo $this->formElementErrors($fileElement); ?><br>
	         <?php echo $this->formSubmit ( $form->get ( 'submit' ) );?>
			<br>
		</div>
		<?php echo $this->form()->closeTag(); ?>
	</div>
	<br>
	<h3>上传注意事项：</h3>
	<ul>
		<li>可上传多个文件。</li>
		<li>只允许上传3D工程文件</li>
	</ul>	
</body>
</html>