<?php
	use Zend\Session\Container;
	$sessionUser = new Container ( 'user' );
?>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php 
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/bootstrap/css/bootstrap.min.css' );
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/style.css' );
	?>
</head>
<body>
	<div style="height: 40px; text-align: center; font-size: 60px; color: #0000ff">3 D 打 印 模 型</div>
	<div class="container">
		<div>
			<ul class="nav navbar-nav navbar-right">
				<?php
				if ($sessionUser->name != NULL) {
				?>	
					<li>欢迎: <?php echo $sessionUser->name?></li>
					<li><a href="/sandi/upload-model">上传模型</a></li>
					<li><a href="/user/index/<?php echo $sessionUser->user_id ?>">我的信息</a></li>
					<li><a href="/sandi/purchase-list">我的订单</a></li>
					<li><a href="/user/logout">退出</a></li>
				<?php
				} 
				else 
				{
				?>
					<li><a href="/user/login">登录</a></li>
					<li><a href="/user/add">注册</a></li>
				<?php
				}
				?>
	        </ul>
		</div>
	</div>
	<div class="container">
		<nav class="navbar navbar-default">
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<?php 
					foreach ( $category as $column => $categoryData):
						echo '<li><a href="/sandi/index/' . $categoryData->category_id . '">' . $categoryData->title . "</a></li>" ;
					endforeach;
					?>
				</ul>
				<form class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
		</nav>
	</div>

	<table>
		<tr height = 50>
			<td span=3>
				2. 上传模型图片文件&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
				 <a href="<?php echo $this->url('sandi', array('action'=>'uploadModelProjectFile', 'id' => $model_id));?>">3. 上传模型工程文件</a>
			</td>
		</tr>
		<tr>
			<td>
				<?php 
					$form = $this->form;
					$form->prepare(); 
				?>
				<?php echo $this->form()->openTag( $form ); ?>
				    <?php $fileElement = $form->get('image-file'); ?>
				    <?php echo $this->formLabel($fileElement); ?>
				    <?php echo $this->formFile($fileElement); ?>
				    <?php echo $this->formElementErrors($fileElement); ?><br>
				    <?php echo $this->formSubmit ( $form->get ( 'submit' ) );?>
				<?php echo $this->form()->closeTag(); ?>
			</td>
			<td width=200px></td>
			<td>
				<table>
					<?php foreach ($modelImageFiles as $modelFile):?>
				    <tr>
						<td width=200px>
							<img src="<?php echo $this->url('sandi', array('action'=>'showImage', 'id' => $model_id, 'subaction' =>$modelFile->id ) );?>" />
							<br><br><?php $file =$modelFile->file_name; echo $file; ?>
						</td>
					</tr>
					<?php endforeach;?>   
				</table>
			</td>
		</tr>
	</table>

	<br>
	<h3>上传注意事项：</h3>
	<ul>
		<li>只保留一副上传的模型图片，最新上传的图片会覆盖以前的。</li>
		<li>只允许上传图片(<strong>JPG, GIF, PNG</strong>)</li>
	</ul>
	
</body>
</html>