<html>
<head>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php 
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/bootstrap/css/bootstrap.min.css' );
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/style.css' );
	?>
</head>
<body class="login-wrap">
	<div style="height: 120px; text-align: center; font-size: 40px;">3D	Logo</div>
	<div class="container">
		<h2 class="form-signin-heading"><?php echo $this->escapeHtml($title); ?></h2>	
		<?php
			$form = $this->form;
			$form->setAttribute ( 'action', $this->url ( 'user', array (
					'action' => 'add' 
			) ) );
			$form->prepare ();
	
			echo $this->form ()->openTag ( $form );
			echo $this->formHidden ( $form->get ( 'user_id' ) );
			echo $this->formRow ( $form->get ( 'alias' ) ) . '<br>';
			echo $this->formRow ( $form->get ( 'password' ) ) . '<br>';
			echo $this->formRow ( $form->get ( 'user_account' ) ) . '<br>';
			// echo $this->formHidden($form->get('last_login'));
			// echo $this->formHidden($form->get('status'));
			echo $this->formRow ( $form->get ( 'profile' ) ). '<br>';
			echo $this->formSubmit ( $form->get ( 'submit' ) );
		?>

	</div>
</body>
</html>
