<?php
	use Zend\Session\Container;
	$sessionUser = new Container ( 'user' );
?>

<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<?php 
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/bootstrap/css/bootstrap.min.css' );
		echo $this->headLink ()->prependStylesheet ( $this->basePath () . '/css/style.css' );
	?>
</head>
<body  class="login-wrap">
	<div style="height: 40px; text-align: center; font-size: 60px; color: #0000ff">3 D 打 印 模 型</div>
	<div class="container">
		<div>
			<ul class="nav navbar-nav navbar-right">
				<?php
				if ($sessionUser->name != NULL) {
					?>	
					<li>欢迎: <?php echo $sessionUser->name?></li>
					<li><a href="/sandi/upload-model">上传模型</a></li>
					<li><a href="/user/index/<?php echo $sessionUser->user_id ?>">我的信息</a></li>
					<li><a href="/user/logout">退出</a></li>
				<?php
				} else {
					?>
					<li><a href="/user/login">登录</a></li>
					<li><a href="/user/add">注册</a></li>
				<?php
				}
				?>
	        </ul>
		</div>
	</div>
	<div class="container">
		<nav class="navbar navbar-default">
			<div class="collapse navbar-collapse navbar-ex1-collapse">
				<ul class="nav navbar-nav">
					<?php 
					foreach ( $category as $column => $categoryData):
						echo '<li><a href="/sandi/index/' . $categoryData->category_id . '">' . $categoryData->title . "</a></li>" ;
					endforeach;
					?>
				</ul>
				<form class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>
			</div>
		</nav>
	</div>
	<br>
	<table class="table">
		<tr>
			<th>昵称</th>
			<th>帐号</th>
			<th>最后登录时间</th>
			<th>... ...</th>
		</tr>
		<tr>
			<td><img src="<?php echo $this->url('user', array('action'=>'showAvarta', 'id' => $user[0]["user_id"]));?>" /></td>
			<td><?php echo $this->escapeHtml($user[0]["user_account"]);?></td>
			<td><?php echo $this->escapeHtml($user[0]["last_login"]);?></td>

			<td><a
				href="<?php echo $this->url('user', array('action'=>'edit', 'id' => $user[0]["user_id"]));?>">修改用户信息</a></td>
		</tr>
	</table>
	
	<div><a href="<?php echo $this->url('user', array('action'=>'uploadAvatar', 'id' =>$user[0]["user_id"]));?>">上传头像</a></div>
	
	<div><a href="<?php echo $this->url('user', array('action'=>'showAvarta', 'id' =>$user[0]["user_id"]));?>">查看头像</a></div>