<?php
//ini_set('default_charset','utf-8');
$title = 'ำรปงตวยผ';
//$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title);?></h1>

<?php
$url = $this->url('user', array(
    'action' => 'login',
));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    ีสบลฃบ<input type="text" name="user_account" value="" /><br>
    รÜย๋ฃบ <input type="text" name="password" value="" /><br>
    <input type="submit" name="login" value="ตวยผ" />
</div>
</form>



